ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Controllers/ConvenioController.cs
using Amil.AppHospitais.APIClient;
using Amil.AsmWebCad.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO = Amil.AppHospitais.DTO;

namespace Amil.AsmWebCad.UI.Controllers
{
    public class ConvenioController : Controller
    {
        //
        // GET: /Convenio/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Convenio/{id}
        public ActionResult Edit(int id = 0)
        {
            var convenioClient = new ConvenioClient(Session);
            DTO.Convenio result = null;
            if (id > 0)
                result = convenioClient.ListarPorId(id);
            ViewBag.TiposConvenio = new List<SelectListItem>();
            ViewBag.TiposConvenio.Add(new SelectListItem { Value = "1", Text = "Grupo Amil" });
            ViewBag.TiposConvenio.Add(new SelectListItem { Value = "2", Text = "Particular" });
            ViewBag.TiposConvenio.Add(new SelectListItem { Value = "0", Text = "Outros Convênios" });

            return View(result);
        }
        [HttpPost]
        public bool Edit(ConvenioViewModel convenio)
        {
            //ModelState.Remove("CodCorporativo");
            //ModelState.Remove("RegistroANS");
            //if (!ModelState.IsValid)
            //    return false;

            if (convenio.Id == 0)
                convenio.isAtivo = true;

            var convenioDTO = new DTO.Convenio()
            {
                Id = convenio.Id,
                RegistroANS = convenio.RegistroANS,
                CodCorporativo = convenio.CodCorporativo,
                isElegibilidade = convenio.isElegibilidade,
                isAtivo = convenio.isAtivo,
                TipoConvenio = convenio.TipoConvenio,
                Nome = convenio.Nome,
                NomeAbreviado = convenio.NomeAbreviado,
            };

            var convenioClient = new ConvenioClient(Session);
            var id = convenioClient.Gravar(convenioDTO);
            return (id > 0);
        }
        public PartialViewResult GridConvenios()
        {
            var client = new ConvenioClient(Session);
            var result = client.Listar();
            return PartialView("_GridConvenios", result);
        }
    }
}

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Controllers/PerfilController.cs
using System;
using System.Web.Mvc;
using System.Linq;
using Amil.AppHospitais.DTO;
using Amil.AppHospitais.APIClient;
using Amil.AsmWebCad.UI.Models;
using Amil.AsmWebCad.UI.Resources;
using Amil.AsmWebCad.Utils;
using System.Collections.Generic;
using Newtonsoft.Json;
using Amil.AsmWebCad.UI.Helpers;

namespace Amil.AsmWebCad.UI.Controllers
{
    public class PerfilController : BaseController
    {
        [SessionTimeout]
        public ActionResult Pesquisa(string limpar = "")
        {
            var perfilModel = (PerfilModel)Session["perfilModel"];
            JsonResult result;

            try
            {
                var client = new PerfilClient(Session);
                var lstSistemaDTO = new List<SistemaDTO>();
                var sistemaClient = new SistemaClient(Session);
                var sistema = new SistemaDTO();

                lstSistemaDTO = sistemaClient.Listar(sistema);

                ViewBag.SistemaBag = new SelectList(lstSistemaDTO, "Id", "Descricao");

                if (perfilModel == null || limpar == "S")
                {
                    var novoPerfilModel = new PerfilModel()
                    {
                        Id = 0,
                        Codigo = "",
                        Descricao = "",
                        IdSistema = 0,
                        PrimeiroAcesso = "S" //2804

                    };

                    return View(novoPerfilModel);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return View(perfilModel);

        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult Pesquisa(FormCollection formCollection)
        {
            JsonResult result;

            try
            {
                var descricao = string.IsNullOrEmpty(formCollection["descricao"]) ? string.Empty : formCollection["descricao"];
                var codigo = string.IsNullOrEmpty(formCollection["codigo"]) ? string.Empty : formCollection["codigo"];
                var sistema = string.IsNullOrEmpty(formCollection["sistema"]) ? "0" : formCollection["sistema"]; 

                PerfilDTO filtroPerfil = new PerfilDTO()
                {
                    IdSistema = Convert.ToInt32(sistema),
                    Codigo = codigo,
                    Descricao = descricao
                };

                PagedResult<PerfilDTO> lstPerfilDTO;

                var client = new PerfilClient(Session);
                var lista = client.Listar(filtroPerfil);
                var paging = formCollection.ToPagingDTO();

                foreach (var perfil in lista)
                {
                    perfil.Sistema = new SistemaClient(Session).Obter(new SistemaDTO() { Id = perfil.IdSistema }).Descricao;
                }

                lstPerfilDTO = lista.ToPagedResult(paging.Offset, paging.Limit, paging.Order);

                result = JsonFromPagedList(lstPerfilDTO);

                var perfilModel = new PerfilModel()
                {
                    Id = filtroPerfil.Id,
                    Codigo = filtroPerfil.Codigo,
                    Descricao = filtroPerfil.Descricao,
                    IdSistema = filtroPerfil.IdSistema,
                    PrimeiroAcesso = "N"   //2804
                };

                Session["perfilModel"] = perfilModel;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult Manutencao(FormCollection formCollection)
        {
            JsonResult result;

            try
            {
                var json = formCollection["json"];
                var perfilModel = JsonConvert.DeserializeObject<PerfilModel>(json);
                var client = new PerfilClient(Session);

                var perfilPesquisa = new PerfilDTO
                {
                    Codigo = perfilModel.Codigo
                };

                var perfilExiste = client.ValidarNovo(perfilPesquisa);

                var perfilDTO = new PerfilDTO();

                perfilDTO.Id = perfilModel.Id;
                perfilDTO.Codigo = perfilModel.Codigo;
                perfilDTO.Descricao = perfilModel.Descricao;
                perfilDTO.IdSistema = perfilModel.IdSistema;

                if (perfilExiste && perfilModel.Id == 0)
                {
                    result = Json(new { Result = 0, Erro = true, Mensagem = "Código de Perfil (" + perfilModel.Codigo + ") já cadastrado." }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var novoPerfil = client.Gravar(perfilDTO);

                    result = Json(new { Result = novoPerfil, Erro = false }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }
 
            return result;
        }

        [SessionTimeout]
        public ActionResult Manutencao()
        {
            var perfilViewModel = new CadastraPerfilViewModel();

            try
            {
                var parameters = SecurityHelper.GetRequestParams();
                var idPerfil = DataParser.Parse(parameters["idPerfil"], 0);
                var client = new PerfilClient(Session);

                //var perfilModel = new PerfilModel();
                perfilViewModel.Id = 0;

                // Editar Perfil
                if (idPerfil > 0)
                {
                    // carrega o perfil e popula os campos
                    var perfilClient = new PerfilClient(Session);
                    var perfilDTO = perfilClient.Obter(new PerfilDTO(){ Id = idPerfil});

                    perfilViewModel.Id = perfilDTO.Id;
                    perfilViewModel.IdSistema = perfilDTO.IdSistema;
                    perfilViewModel.Descricao = perfilDTO.Descricao;
                    perfilViewModel.Codigo = perfilDTO.Codigo;
                }

                ViewBag.SistemaBag = CarregarSistemas(perfilViewModel.Id);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(perfilViewModel);
        }


        private SelectList CarregarSistemas(int valorSelecionado)
        {
            var itens = new List<SelectListItem>();
            var lstSistemaDTO = new List<SistemaDTO>();
            var sistemaClient = new SistemaClient(Session);
            var sistema = new SistemaDTO();

            lstSistemaDTO = sistemaClient.Listar(sistema);

            foreach (var sistemaDTO in lstSistemaDTO)
            {
                itens.Add(new SelectListItem
                {
                    Value = sistemaDTO.Id.ToString(),
                    Text = sistemaDTO.Descricao,
                    Selected = sistemaDTO.Id == valorSelecionado
                });
            }

            return new SelectList(itens, "Value", "Text", valorSelecionado);
        }

        [HttpPost]
        public ActionResult Exclusao(FormCollection formCollection)
        {
            JsonResult result;

            try
            {
                var idPerfil = DataParser.Parse(formCollection["idPerfil"], 0);
                var perfil = new PerfilDTO() { Id = idPerfil };
                var client = new PerfilClient(Session);
                var perfilModulo = new PerfilClient(Session).Obter(new PerfilDTO() { Id = idPerfil });

                var perfilModuloClient = new PerfilModuloSistemaClient(Session);
                var listaSelecionados = perfilModuloClient.ListarPorPerfil(new PerfilModuloSistemaDTO() { Perfil = perfilModulo });

                if (listaSelecionados.Count == 0)
                {
                    client.Excluir(perfil);

                    result = Json(new { Result = 1, Erro = false }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = Json(new { Result = 0, Erro = true, Mensagem = "Não foi possivel excluir, Existem Modulos associados a este perfil." }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [SessionTimeout]
        public PartialViewResult CarregarModulos(int Id)
        {
            var perfilModulo = new PerfilClient(Session).Obter(new PerfilDTO() { Id = Id });

            int idSistema = perfilModulo.IdSistema;
            // listar os modulos do sistema
            var moduloClient = new ModuloSistemaClient(Session);
            var listaTodos = moduloClient.Listar(idSistema);

            // todos os modulos do perfil
            var perfilModuloClient = new PerfilModuloSistemaClient(Session);
            var listaSelecionados = perfilModuloClient.ListarPorPerfil(new PerfilModuloSistemaDTO() { Perfil = perfilModulo });

            if (listaTodos == null) listaTodos = new List<ModuloDTO>();

            var listaNaoSelecionado = new List<ModuloDTO>(listaTodos);

            List<ModuloDTO> listaModuloSelecionados = new List<ModuloDTO>();

            foreach (var moduloSelecionado in listaSelecionados)
            {

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/Shared/_Layout.cshtml
@using Amil.AsmWebCad.UI.Resources;

<!DOCTYPE html>

<html>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=11,IE=EDGE">
    <title>@ViewBag.Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=11,IE=EDGE">
    @Styles.Render("~/Content/css",
                    "~/Content/UI")

    @Scripts.Render("~/bundles/jquery",
                    "~/bundles/jqueryval",
                    "~/bundles/modernizr",
                    "~/bundles/plugins",
                    "~/bundles/bootstrap",
                    "~/bundles/AmilFramework",
                    "~/bundles/AmilFrameworkMapas",
                    "~/bundles/jquery-ui")

    @RenderSection("SectionHead", false)
</head>
<body>
    <div id="wrapper">
        <div class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="row">
                <div class="col-sm-3 col-md-2 col-lg-2 col-xl-2">
                    <h1>
                        <img alt="Amil" src="~/Content/Imagens/logoAmericas.png"  height="60" style="margin-top:-5px;" title="@Resource.Titulo_CadWeb"></h1>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6">
                    <h1>Americas - Cadastros e Configurações </h1>
                </div>
                <div class="col-sm-3 col-md-4 col-lg-4 col-xl-4">
                    <ul class="nav navbar-top-links navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 1px; margin-top: 55px; margin-left: 10px; min-height: 20px;">
                                <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                @*                           
                            <li>
                                <a href="#"><i class="fa fa-ellipsis-h fa-fw"></i>Alterar Senha</a>
                            </li>
                            <li class="divider"></li>
                            *@
                                <li>
                                    <a href="~/Login/LogOut"><i class="fa fa-sign-out fa-fw"></i>Sair</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <span class="nomeUsuarioLogado">Bem vindo(a) @TempData["NomeUsuario"] </span>
                    @{
                        TempData.Keep("NomeUsuario");
                    }
                </div>
            </div>

            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#"><i class="fa fa-file-text fa-fw"></i>&nbsp;Aplicativo Hospitais<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index", "ConfigApp")">Configurações</a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Unidades", "AppHospitais")">Unidades</a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Index", "Convenio")">Convênios</a>
                                </li>
                            </ul>

                        </li>
                        <li>
                            <a href="#"><i class="fa fa-file-text fa-fw"></i>&nbsp;Indicadores Real Time<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Pesquisa", "UnidadeNow")">Unidades</a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Pesquisa", "EspecialidadePorUnidadeNow", new { limpar = "S" })">Especialidades</a>
                                </li>

                            </ul>

                        </li>
                        <li>
                            <a href="#"><i class="fa fa-file-text fa-fw"></i>&nbsp;Painel de Filas do PS<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/ConfigPainel/Index">Configurações</a>
                                </li>
                            </ul>

                        </li>

                        <li>
                            <a href="#"><i class="fa fa-file-text fa-fw"></i>&nbsp;Controle de Acesso<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Pesquisa", "Usuario", new { limpar = "S" })">Usuários</a>
                                </li>

                                <li>
                                    <a href="@Url.Action("Pesquisa", "Perfil", new { limpar = "S" })">Perfis</a>
                                </li>

                            </ul>

                        </li>

                    </ul>
                </div>
            </div>

        </div>

        <div id="page-wrapper">
            <h3 class="page-header">@ViewBag.Title</h3>
            <div>
                @RenderBody()
            </div>
            @*           
            <div class="version">
                @Html.Label(@Resource.VersaoPortal)
            </div>
                *@
            @Html.Partial("_ModalWaitPartial")
        </div>

    </div>

    <script type="text/javascript">
        $(function () {
            $(document).ajaxError(function (event, request, settings) {
                if (request.status === 403) {
                    window.location = '../Login/Login?RetunUrl=' + window.location.pathname;
                }
            });
        });

        var pathArray = window.location.pathname.split('/');
        var idleTime = 0;
        $(document).ready(function () {
            var UnlockProfissional = '@Url.Action("UnlockProfissional", "Profissional")';
            //Incrementa o idleTime a cada minuto.
            var idleInterval = setInterval(timerIncrement, 60000); // 1 minuto

            //Zera o idleTime no movimento do mouse.
            $(this).mousemove(function (e) {
                idleTime = 0;
            });
            $(this).keypress(function (e) {
                idleTime = 0;
            });

        });

        function timerIncrement() {

            var sessionTime = '@System.Configuration.ConfigurationManager.AppSettings["SessionTime"]';
            idleTime = idleTime + 1;
            if (idleTime > Number(sessionTime)) { // 20 minutos, configurado no web.config
                if (sessionStorage.getItem("contador") != null)
                    sessionStorage.clear();

                window.location.pathname = '@Url.Action("Logout", "Login")';
            }
        }

        function recordeCloseTime() {
            validNavigation = true;
        }

        function disableF5(e) {
            if ((e.which || e.keyCode) == 116) {
                validNavigation = true;
                e.preventDefault();
            }
        };

    </script>


    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)
</body>
</html>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/Shared/_LayoutSemMenu.cshtml
@using Amil.AsmWebCad.UI.Resources;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Resource.NomePortal - @ViewBag.Title</title>
    <meta http-equiv="X-UA-Compatible" content="IE=11,IE=EDGE">
    @Styles.Render("~/Content/css",
                    "~/Content/UI")

    @Scripts.Render("~/bundles/jquery",
                    "~/bundles/jqueryval",
                    "~/bundles/modernizr",
                    "~/bundles/plugins",
                    "~/bundles/bootstrap",
                    "~/bundles/AmilFramework",
                    "~/bundles/AmilFrameworkMapas",
                    "~/bundles/jquery-ui")
</head>
<body>
    <div id="wrapper">
        <div  class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="row" >
                <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
                <div class="col-sm-9 col-md-9 col-lg-9 col-xl-9">
                    <h1>Americas - Cadastros e Configurações </h1>
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">
                    <h1> <img alt="Amil" src="~/Content/Imagens/logoAmericas.png"  height="60" style="margin-top:-5px;" title="@Resource.Titulo_CadWeb"></h1>
                </div>
            </div>
        </div>
        <div id="page-wrapper" style="margin: 0 0 0 0;">
            <div class="panel panel-primary" style="width: 500px; margin: 50px auto 0 auto;">
                @RenderBody()
            </div>
            @Html.Partial("_ModalWaitPartial")
        </div>
    </div>
    <div class="footer-height">
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/Shared/_ModalWaitPartial.cshtml
<div class="modal fade" id="js-loading-bar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4>Processando</h4>
                <div class="progress progress-popup">
                    <div id="progressbar" class="progress-bar">
                        <div class="progress-label"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>