ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Controllers/EspecialidadePorUnidadeNowController.cs
using Amil.AsmWebCad.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Amil.AppHospitais.DTO;
using Amil.AsmWebCad.Utils;
using Amil.AsmWebCad.UI.NowWCF;
using System.IO;
using Amil.AsmWebCad.UI.Helpers;
using Amil.AppHospitais.BLL;

namespace Amil.AsmWebCad.UI.Controllers
{
    public class EspecialidadePorUnidadeNowController : BaseController
    {
        //
        // GET: /EspecialidadePorUnidadeNow/

        public ActionResult Pesquisa(string limpar = "", string modal = "")
        {
            EspecialidadeNowModel especialidadeNowModel = new EspecialidadeNowModel();
            if (modal == "S")
            {

                especialidadeNowModel.IdEspecialidade = 1;
                especialidadeNowModel.Descricao = "TESTE";

            }
            else if (especialidadeNowModel == null || limpar == "S")
            {


                especialidadeNowModel.IdEspecialidade = 0;
                especialidadeNowModel.Descricao = "";
                especialidadeNowModel.PrimeiroAcesso = "S";

                Session["especialidadeNowModel"] = null;


            }

            return View(especialidadeNowModel);


        }

        [HttpPost]
        public ActionResult Pesquisa(FormCollection formCollection)
        {
            JsonResult result = null;

            try
            {
                var lstSpec = new List<NowSpecialtyDTO>();
                var paging = formCollection.ToPagingDTO();
                PagedResult<NowSpecialtyDTO> lstSpecDTO;

                lstSpec = new ServiceClient().GetNowSpecialties();

                paging.Order = "Specialty";
                lstSpecDTO = lstSpec.ToPagedResult(paging.Offset, paging.Limit, paging.Order);

                result = JsonFromPagedList(lstSpecDTO);

            }
            catch (TimeoutException ex)
            {
                ModelState.AddModelError("Timeout", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;

        }


        public ActionResult Manutencao()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Manutencao(FormCollection formcollection)
        {
            return View();
        }

        public PartialViewResult CarregarPesquisa(string Nome)
        {
            var especialidadeNowModel = (EspecialidadeNowModel)Session["EspecialidadeNowModel"];
            //if (UnidadeNowModel == null)
            //{
            //    UnidadeNowModel = new UnidadeNowModel();

            especialidadeNowModel = new EspecialidadeNowModel();

            especialidadeNowModel.IdEspecialidade = 1;
            especialidadeNowModel.Descricao = Nome;

            ViewBag.NomeBag = "TESTE";
            //}

            return PartialView("_PesquisaModal");
        }

    }
}

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/EspecialidadePorUnidadeNow/Manutencao.cshtml
@{
    ViewBag.Title = "Manutencao";
}

<h2>Manutencao</h2>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/EspecialidadePorUnidadeNow/Pesquisa.cshtml
@using Amil.AsmWebCad.UI.Resources
@model Amil.AsmWebCad.UI.Models.EspecialidadeNowModel


@{
    ViewBag.Title = Resource.ListaEspecialidades;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section SectionHead{
    @Scripts.Render("~/bundles/unidadeNow")

    <script type="text/javascript">
        $(document).ready(function () {
            Unidade.Urls.PesquisaEspecialidade = '@Url.Action("Pesquisa", "EspecialidadePorUnidadeNow")';
            Unidade.Urls.ManutencaoEspecialidade = '@Url.Action("Manutencao", "EspecialidadePorUnidadeNow")';
            Unidade.Urls.ExclusaoEspecialidade = '@Url.Action("Exclusao", "EspecialidadePorUnidadeNow")';
            Unidade.Urls.limparSession = '@Url.Action("Limpar", "EspecialidadePorUnidadeNow")';
            Unidade.Urls.ValidarAcessoPesquisa = '@Url.Action("ValidarAcessoPesquisa", "EspecialidadePorUnidadeNow")';

            //RL - Token - Mapeamento da controler e sua action
            Unidade.Urls.GerarToken = '@Url.Action("GerarToken", "EspecialidadePorUnidadeNow")';


            Especialidade.Titulo = '@Resource.EspecialidadeNow';
            PesquisaEspecialidade.Mensagens.SucessoExclusao = '@Resource.MensagemSucessoExclusao';
            PesquisaEspecialidade.Mensagens.ConfirmacaoExclusao = '@Resource.MensagemConfirmacaoExclusao';
            PesquisaEspecialidade.Mensagens.AlertaPesquisaComCampos = '@Resource.AlertaTelaPesquisaUsuariosCampos';
            PesquisaEspecialidade.Inicializar();


            $("#txtNomeFiltro").on("input", function () {
                var regexp = /[^a-zA-ZÀ-ú. ]/g;

                if (this.value.match(regexp)) {
                    $(this).val(this.value.replace(regexp, ''));
                }

                $(this).val(this.value.toLowerCase().replace(/(^| )(\w)/g, function (s) { return s.toUpperCase() }));
                $(this).val(this.value.replace(/( )+/g, ' '));

            });

        });
    </script>
}


<form class="form-horizontal" role="form" onsubmit="return false;" id="search-form">
    <div class="panel-full">
        <div class="panel panel-primary">
            <div class="panel-heading">
                @Resource.Pesquisa
                <div class="pull-right" data-toggle="collapse" data-target="#pequisaUsuario">
                    <button type="button" class="btn btn-default btn-xs" data-toggle="button">
                        <i class="fa fa-minus-square"></i>
                    </button>
                </div>
            </div>
            <div class="panel-body collapse in" id="pequisaUnidade">
                <div class="form-group">

                    <div class="row">
                        <label class="col-lg-2 control-label">@Resource.Descricao:</label>
                        <div class="col-lg-9">
                            @Html.TextBoxFor(a => a.Descricao, (string)ViewBag.NomeBag, (object)new { @class = "form-control", @id = "txtNomeFiltro", @maxlength = 50 })
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <label class="col-lg-2 control-label">@Resource.CodigoCorporativo:</label>
                        <div class="col-lg-9">
                            <input class="form-control" type="text" id="txtCodigoIntegracao" maxlength="15" />
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <label class="col-lg-2 control-label">@Resource.Status:</label>
                        <div class="col-lg-3">
                            <select id="ddlStatusFiltro" class="form-control">
                                <option selected="selected" value="0">@Resource.Todos</option>
                                <option value="1">@Resource.Ativo</option>
                                <option value="2">@Resource.Inativo</option>
                            </select>
                        </div>
                    </div>
                    <br />
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <button type="submit" class="btn btn-primary"  title="@Resource.TituloBotaoPesquisar" data-toggle="modal" data-target="#unidadeModal">@Resource.Pesquisar</button>
                        <button type="reset" class="btn btn-outline btn-primary" onclick="PesquisaUnidade.Limpar();" title="@Resource.TituloBotaoLimpar">@Resource.Limpar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="panel-full">
    <div class="pull-left">
        <div class="form-actions">
            <button title="@Resource.TituloBotaoNovo" id="btnInserir" class="btn btn-primary btnBotaoGridDireita" type="button" >
                <i class="glyphicon glyphicon-plus"></i>
            </button>
        </div>
    </div>
    <div id="dttUnidadeDivisoes" class="dataTables_wrapper form-inline">
        <table id="grvUnidadeDivisoes" style="cursor: pointer" data-dtid="idProtocolo" class="table table-striped table-bordered dataTable">
            <thead>
                <tr>
                    <th data-dtcolumn="Descricao" data-column-class="width-60">@Resource.Nome</th>
                    <th data-dtcolumn="UF">@Resource.UF</th>
                    <th data-dtcolumn="Base" data-column-class="align-mid">@Resource.Base</th>
                    <th data-dtcolumn="CodigoBase" data-column-class="align-mid">@Resource.CodigoBase</th>
                    <th data-dtaction="Acoes" data-column-class="align-mid">@Resource.Acoes</th>
                    <th data-dtcolumn="Id" data-column-class="hide"></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>