ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Models/Login/UnidadeViewModel.cs
using Amil.AsmWebCad.UI.Resources;
using System.ComponentModel.DataAnnotations;

namespace Amil.AsmWebCad.UI.Models.Login
{
    public class UnidadeViewModel
    {
        [Required(ErrorMessageResourceName = "Login_UnidadeObrigatorio", ErrorMessageResourceType = typeof(Resource))]
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Controllers/UnidadeNowController.cs
using Amil.AppHospitais.DTO;
using Amil.AsmWebCad.UI.Models;
using Amil.AsmWebCad.Utils;
using Amil.AsmWebCad.UI.Helpers;
using System.Collections.Generic;
using Newtonsoft.Json;
using System;
using System.Web.Mvc;
using Amil.AppHospitais.APIClient;
using Newtonsoft.Json.Converters;
using Amil.AsmWebCad.UI.NowWCF;


namespace Amil.AsmWebCad.UI.Controllers
{
    [SessionTimeout]
    //[ValidaTokenFilter("WEBCAD_P2121")]
    public class UnidadeNowController : BaseController
    {
        #region Unidades

        public ActionResult Pesquisa(string limpar = "")
        {
            var UnidadeNowModel = (UnidadeNowModel)Session["unidadeNowModel"];
            if (UnidadeNowModel == null || limpar == "S")
            {
                UnidadeNowModel = new UnidadeNowModel();

                UnidadeNowModel.Id = 0;
                UnidadeNowModel.Nome = "";
                UnidadeNowModel.CodigoCorporativo = "";
                UnidadeNowModel.PrimeiroAcesso = "S";

                Session["UnidadeNowModel"] = null;

            }

            return View(UnidadeNowModel);

        }

        [HttpPost]
        public ActionResult Pesquisa(FormCollection formCollection)
        {

            JsonResult result = null;

            try
            {
                var nome = formCollection["nome"];
                var tipo = formCollection["tipo"];

                var lstSpec = new List<NOW_UNIDADE>();
                var paging = formCollection.ToPagingDTO();
                PagedResult<NOW_UNIDADE> lstSpecDTO;

                var client = new ServiceClient();

                if (tipo == "0")
                {
                    lstSpec = client.UnidadeDadosNome(nome);
                }
                else
                {
                    lstSpec = client.UnidadeDadosCd(nome);
                }


                paging.Order = "NM_UNIDADE";
                lstSpecDTO = lstSpec.ToPagedResult(paging.Offset, paging.Limit, paging.Order);

                result = JsonFromPagedList(lstSpecDTO);

            }
            catch (TimeoutException ex)
            {
                ModelState.AddModelError("Timeout", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            var unidadeNowModel = new UnidadeNowModel();

            unidadeNowModel.Id = 0;
            unidadeNowModel.Nome = "";// unidadeDTO.Nome;
            unidadeNowModel.CodigoCorporativo = "";// unidadeDTO.CodigoCorporativo;
            unidadeNowModel.Status = "T";
            unidadeNowModel.PrimeiroAcesso = "N";

            Session["unidadeNowModel"] = unidadeNowModel;

            return result;

        }


        public ActionResult Manutencao()
        {
            var graficoUnidade = new GraficoUnidadeNowModel();
            var parameters = SecurityHelper.GetRequestParams();
            var unidadeNowModel = new UnidadeNowModel();
            UnidadeAppNowDTO unidadeDTO = new UnidadeAppNowDTO();
            var idUnidade = DataParser.Parse(parameters["idUnidade"], 0);
            var serviceNow = new ServiceClient();

            //ViewBag.SistemaBag = new SelectList(lstSistemaDTO, "Id", "Descricao");
            var lstEstados = serviceNow.Estado(); // ID_UF, DESCRICAO
            ViewBag.UF = new SelectList(lstEstados, "ID_UF", "ID_UF");

            var lstRegional = serviceNow.Regional();
            ViewBag.Regional = new SelectList(lstRegional, "ID_REGIONAL", "NM_REGIONAL");

            var lstRisco = serviceNow.EscalaRisco();
            ViewBag.EscalaRisco = new SelectList(lstRisco, "ID_ESCALA_RISCO", "NM_ESCALA_RISCO");

            var lstBase = serviceNow.BaseWpd();
            ViewBag.Base = new SelectList(lstBase, "ID_BASE_DADOS", "NOME");

            ViewBag.StatusBag = BuscarAtivoInativo(null);

            if (idUnidade > 0)
            {
                var unidade = serviceNow.UnidadeDadosId(idUnidade);
                ViewBag.RegionalUF = serviceNow.RegionalUF(unidade.CM_REGIONAL.CM_FILIAL_UF.ID_UF);

                unidadeNowModel.Nome = unidade.NM_UNIDADE;
                unidadeNowModel.UF = unidade.CM_REGIONAL.CM_FILIAL_UF.ID_UF;
                unidadeNowModel.Regional = unidade.CM_REGIONAL.ID_REGIONAL.ToString();
                unidadeNowModel.EscalaRisco = unidade.CM_ESCALA_RISCO.ID_ESCALA_RISCO.ToString();
                unidadeNowModel.BaseWPD = unidade.CM_BASE_DADOS_WPD.ID_BASE_DADOS.ToString();
                unidadeNowModel.CodigoCorporativo = unidade.CD_UNIDADE;
                unidadeNowModel.Status = unidade.FL_ATIVA.ToString();
                unidadeNowModel.Id = (int)unidade.ID_UNIDADE; ;

                //ddlBase.SelectedValue = _unity.CM_BASE_DADOS_WPD == null
                //    ? "0"
                //    : _unity.CM_BASE_DADOS_WPD.ID_BASE_DADOS.ToString();


            }

            return View(unidadeNowModel);
        }

        [HttpPost]
        public ActionResult Manutencao(FormCollection formCollection)
        {
            JsonResult result;

            try
            {
                var json = formCollection["json"];
                var format = "dd/MM/yyyy";
                var dateTimeConverter = new IsoDateTimeConverter { DateTimeFormat = format };
                var unidadeNowModel = JsonConvert.DeserializeObject<UnidadeNowModel>(json, dateTimeConverter);
                UnidadeAppNowDTO unidade = new UnidadeAppNowDTO();
                UnidadeAppNowDTO unidadePesquisa = new UnidadeAppNowDTO();

                unidade.Id = unidadeNowModel.Id;
                unidade.Nome = unidadeNowModel.Nome;
                unidade.UF = unidadeNowModel.UF;
                unidade.Regional = unidadeNowModel.Regional;
                unidade.EscalaRisco = unidadeNowModel.EscalaRisco;
                unidade.Base = unidadeNowModel.BaseWPD;
                unidade.CodigoCorporativo = unidadeNowModel.CodigoCorporativo;
                unidade.Ativo = unidadeNowModel.Ativo;
                unidade.Id = unidadeNowModel.Id;


                if (!Util.ValidarNome(unidade.Nome))
                {
                    ModelState.AddModelError("", "Nome inválido");
                    return Json(new { Result = 0, Erro = true, Mensagem = "Nome inválido" }, JsonRequestBehavior.AllowGet);
                }

                var unidadeNowClient = new UnidadeNowClient(Session);

                if (unidade.Id > 0)
                {
                    var idUnidade = unidadeNowClient.AlterarUnidade(unidade);
                    result = Json(new { Result = idUnidade, Erro = false }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    unidadePesquisa = unidadeNowClient.Obter(unidade.Id);
                    if (unidadePesquisa == null)
                    {
                        var novaUnidade = unidadeNowClient.CadastrarUnidade(unidade);
                        result = Json(new { Result = novaUnidade, Erro = false }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {

                        result = Json(new { Result = 0, Erro = true, Mensagem = "Usuário já cadastrado" }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Exclusao(FormCollection formCollection)
        {
            JsonResult result;

            try
            {
                var idUnidade = DataParser.Parse(formCollection["idUnidade"], 0);

                var unidadeNowClient = new UnidadeNowClient(Session);

                unidadeNowClient.Excluir(idUnidade);

                result = Json(new { Result = 1, Erro = false }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }


        public ActionResult ValidarAcessoPesquisa()
        {
            JsonResult result;

            try
            {
                var client = new ServiceClient();

                var lstSpec = new List<NOW_UNIDADE>();
                PagedResult<NOW_UNIDADE> lstSpecDTO;

                lstSpec = client.UnidadeDadosNome("IVAN");

                result = Json(new { Result = "true", Erro = false, Mensagem = "Acesso OK" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }

        #endregion


        #region Especialidades

        public ActionResult ListarEspecialidades(FormCollection formCollection)
        {
            var idUnidade = string.IsNullOrEmpty(formCollection["IdUnidade"]) ? 0 : Convert.ToInt32(formCollection["IdUnidade"]);
            JsonResult result = null;

            try
            {
                var lstSpec = new List<EspecialidadeDTO>();
                var paging = formCollection.ToPagingDTO();
                PagedResult<EspecialidadeDTO> lstSpecDTO;

                lstSpec = new ServiceClient().UnidadeEspecialidade(idUnidade);

                paging.Order = "ESPECIALIDADE";

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/UnidadeNow/Pesquisa.cshtml
@using Amil.AsmWebCad.UI.Resources
@model Amil.AsmWebCad.UI.Models.UnidadeNowModel


@{
    ViewBag.Title = Resource.ListaUnidades;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section SectionHead{
    @Scripts.Render("~/bundles/unidadeNow")

    <script type="text/javascript">
        $(document).ready(function () {
            Unidade.Urls.PesquisaUnidade = '@Url.Action("Pesquisa", "UnidadeNow")';
            Unidade.Urls.ManutencaoUnidade = '@Url.Action("Manutencao", "UnidadeNow")';
            Unidade.Urls.ExclusaoUnidade = '@Url.Action("Exclusao", "UnidadeNow")';
            Unidade.Urls.limparSession = '@Url.Action("Limpar", "UnidadeNow")';
            Unidade.Urls.ValidarAcessoPesquisa = '@Url.Action("ValidarAcessoPesquisa", "UnidadeNow")';
            Unidade.Urls.InclusaoEspecialidade = '@Url.Action("Manutencao", "UnidadeNow")';

            //RL - Token - Mapeamento da controler e sua action
            Unidade.Urls.GerarToken = '@Url.Action("GerarToken", "unidadeNow")';


            Unidade.Titulo = '@Resource.UnidadesNow';
            PesquisaUnidade.Mensagens.SucessoExclusao = '@Resource.MensagemSucessoExclusao';
            PesquisaUnidade.Mensagens.ConfirmacaoExclusao = '@Resource.MensagemConfirmacaoExclusao';            
            PesquisaUnidade.Mensagens.AlertaPesquisaComCampos = '@Resource.AlertaTelaPesquisaUsuariosCampos';
            PesquisaUnidade.Mensagens.AlertaNome3Caracteres = '@Resource.AlertaNome3Caracteres';
            PesquisaUnidade.Inicializar();


            $("#txtNomeFiltro").on("input", function () {
                var regexp = /[^a-zA-ZÀ-ú. ]/g;

                if (this.value.match(regexp)) {
                    $(this).val(this.value.replace(regexp, ''));
                }

                $(this).val(this.value.toLowerCase().replace(/(^| )(\w)/g, function (s) { return s.toUpperCase() }));
                $(this).val(this.value.replace(/( )+/g, ' '));
            });

        });
    </script>
}


<form class="form-horizontal" role="form" onsubmit="return false;" id="search-form">
    <div class="panel-full">
        <div class="panel panel-primary">
            <div class="panel-heading">
                @Resource.Pesquisa
                <div class="pull-right" data-toggle="collapse" data-target="#pequisaUsuario">
                    <button type="button" class="btn btn-default btn-xs" data-toggle="button">
                        <i class="fa fa-minus-square"></i>
                    </button>
                </div>
            </div>
            <div class="panel-body collapse in" id="pequisaUsuario">
                <div class="form-group">
                    @Html.HiddenFor(a => a.Status)
                    @Html.HiddenFor(a => a.Tipo)
                    @Html.HiddenFor(a => a.PrimeiroAcesso)
                    <div class="row">
                        <div class="col-md-2">
                            Pesquisar por
                            <select id="ddlTipoFiltro" class="form-control">
                                <option selected="selected" value="0">Descrição</option>
                                <option value="1">Código</option>
                            </select>
                            </div>
                            <div class="col-md-4">
                                &nbsp;
                                <input class="form-control" type="text" id="txtFiltro" maxlength="50" />
                            </div>
                        </div>
                    <br />
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <button type="submit" class="btn btn-primary" onclick="PesquisaUnidade.Pesquisar();" title="@Resource.TituloBotaoPesquisar">@Resource.Pesquisar</button>
                        <button type="reset" class="btn btn-outline btn-primary" onclick="PesquisaUnidade.Limpar();" title="@Resource.TituloBotaoLimpar">@Resource.Limpar</button>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="panel-full">
    <div class="pull-left">
        <div class="form-actions">
            <button title="@Resource.TituloBotaoNovo" id="btnInserir" class="btn btn-primary btnBotaoGridDireita" type="button" >
                <i class="glyphicon glyphicon-plus"></i>
            </button>
        </div>
    </div>
    <div id="dttUnidade" class="dataTables_wrapper form-inline">
        <table id="grvUnidade" style="cursor: pointer" data-dtid="idProtocolo" class="table table-striped table-bordered dataTable">
            <thead>
                <tr>
                    <th data-dtaction="Acoes" data-column-class="align-mid">@Resource.Acoes</th>
                    <th data-dtcolumn="NM_UNIDADE" data-column-class="width-40">@Resource.Nome</th>
                    <th data-dtcolumn="CM_REGIONAL.CM_FILIAL_UF.ESTADOS.ID_UF">@Resource.UF</th>
                    <th data-dtcolumn="CM_BASE_DADOS_WPD.NOME">Base</th>
                    <th data-dtcolumn="CD_UNIDADE" data-column-class="align-mid">@Resource.CodigoBase</th>
                    <th data-dtcolumn="ID_UNIDADE" data-column-class="hide"></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/UnidadeNow/Unidades.cshtml
@{
    ViewBag.Title = "HOME >> Aplicativo Hospitais >> Unidades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-full">
    <div class="BoxConteudoPagina Box98 FloatEsquerdo">
        <!--<div class="BoxFull SitePath">
            <asp:HyperLink ID="hplSiteMapHome" CssClass="SiteMap" runat="server" EnableViewState="False" NavigateUrl="Menu.aspx">Home</asp:HyperLink>
            <asp:Label ID="Label33" runat="server" EnableViewState="False" Text=" >> "></asp:Label>
            <asp:Label ID="Label34" CssClass="SitePathAtual" runat="server" EnableViewState="False" Text="Lista de Unidades"></asp:Label>
        </div>
       -->
        <div class="LinhaTitulo">
            @Html.Label("Titulo", "Lista de Unidades")
          
        </div>
        <div class="LinhaSeparacao"></div>

        <div class="BoxFull">
            <div class="BoxFiltro FloatEsquerdo" style="min-height: 25px; padding-bottom: 10px; padding-top: 10px; width: 100%; padding: 5px;">
                <div class="Box20-100 FloatEsquerdo" style="line-height: 24px; padding-left: 10px;">
                    @Html.Label("Pesquisar por:"):
                </div>
                <div class="Box18-115 FloatEsquerdo">
                    @{
                        List<SelectListItem> listItems = new List<SelectListItem>();
                        listItems.Add(new SelectListItem { Text = "Descrição", Value = "0" });
                        listItems.Add(new SelectListItem { Text = "Código", Value = "1" });                          
                    }

                    @Html.DropDownList("Pesquisa", listItems, new { @class = "form-control", id = "tipoPesquisa" })

                </div>

                <div class="input-group col-md-9">
                    <input type="text" name="edtPesquisar" id="edtPesquisar" class="  search-query form-control" placeholder="Search" />
                    <span class="input-group-btn">
                        <button class="btn btn-danger" type="button">
                            <span class=" glyphicon glyphicon-search"></span>
                        </button>
                    </span>

                    <span class="col-md-2 FloatEsquerdo">
                        @Html.Label("Status:", new { @class = "Box20-100 FloatEsquerdo" } )
                    </span>

                    <span class="col-md-5">
                        @Html.DropDownList("Status", new List<SelectListItem>
                                                    {
                                                        new SelectListItem{ Text="Todos",   Value = "2" },
                                                        new SelectListItem{ Text="Ativo",   Value = "1" },
                                                        new SelectListItem{ Text="Inativo", Value = "0" }
                                                    },
                            new { @class = " form-control ", id = "vlStatus" }
                        )
                    </span>    
                    
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col col-lg-1">
                <a href="@Url.Action("EditarCriarUnidade")" class="btn btn-primary">Incluir</a>
            </div>
            <div class="col-lg-6"></div>
            <div class="col col-lg-4">
                @*<button class="btn btn-secondary" type="button">
                    <i class=" glyphicon glyphicon-export"></i>
                    Exportar Excel
                </button>
                <button class="btn btn-secondary" type="button">
                    <i class=" glyphicon glyphicon-export"></i>
                    Exportar PDF
                </button>*@
            </div>
        </div>
        <div class="">
            @Html.Action("GridUnidades")
        </div>

    </div>
</div>
<script type="text/javascript">

    var tipoPesquisa = '';

    $(function () {

        //Evento campo de pesquisa
        $("#edtPesquisar").on("keyup", function () {
            tipoPesquisa = $("#tipoPesquisa").val();
            var search = $(this).val().toUpperCase();
            var status = $("#vlStatus").val();
            var rows = $("#unidadesGrid tbody tr");

            var trataRetStatus = TrataEnumStatus(status);

            //Pesquisa codigo
            if (tipoPesquisa == 1) {
                $.each(rows, function () {
                    var td = $(this).children("td")[0];
                    var tdStatus = $(this).children("td")[2];
                    var codigo = $(td).text().toUpperCase();
                    var descStatus = $(tdStatus).text().toUpperCase();

                    if ($(td).text().indexOf(search) < 0 || (trataRetStatus != 'TODOS' && descStatus != trataRetStatus)) {
                        $(this).hide();
                    }
                    else {
                        $(this).show();
                    }
                });
            }
                //Pesquisa Descricao
            else if (tipoPesquisa == 0 && search.length >= 3) {
                $.each(rows, function () {
                    var td = $(this).children("td")[1];
                    var tdStatus = $(this).children("td")[2];
                    var descricao = $(td).text().toUpperCase();
                    var descStatus = $(tdStatus).text().toUpperCase();

                    if (descricao.indexOf(search.toUpperCase()) < 0 || ( trataRetStatus != 'TODOS' && descStatus != trataRetStatus) ) {
                        $(this).hide();
                    }
                    else {
                        $(this).show();
                    }
                });
            }
            else
                $.each(rows, function () {
                    var tdStatus = $(this).children("td")[2];
                    var descStatus = $(tdStatus).text().toUpperCase();

                    if ( (trataRetStatus != 'TODOS' && descStatus != trataRetStatus) ) {
                        $(this).hide();
                    }
                    else {
                        $(this).show();
                    }
                });
        });



        //Evento combo de status
        $("#vlStatus").on("change", function () {
            tipoPesquisa = $("#tipoPesquisa").val();
            var retStatus = $("#vlStatus").val();
            var rows = $("#unidadesGrid tbody tr");

            var valDescricao = $("#edtPesquisar").val().toUpperCase();


            var trataRetPesq = TrataEnumStatus(retStatus);

            $.each(rows, function () {
                var tdCodigo = $(this).children("td")[0];
                var tdDescricao = $(this).children("td")[1];
                var td = $(this).children("td")[2];
                var pesquisa = '';

                if (tipoPesquisa == '1') {
                    pesquisa = $(tdCodigo).text().toUpperCase();
                }
                else {
                    pesquisa = $(tdDescricao).text().toUpperCase();
                }

                if (trataRetPesq == 'TODOS') {
                    if (pesquisa.length > 0 && pesquisa.includes(valDescricao) == true) {
                        $(this).show();
                    }
                    else if ( pesquisa.includes(valDescricao) == true ) {
                        $(this).show();
                    }
                    else {
                        $(this).hide();
                    }
                }
                else {
                    if ( ($(td).text().toUpperCase() == trataRetPesq)  &&  (pesquisa.includes(valDescricao) == true) ) {
                        $(this).show();
                    }
                    else {
                        $(this).hide();
                    }
                }
            });

        });

        //Função que trata o retorno do status
        function TrataEnumStatus(retPesquisa) {
            var trataRetPesq = '';

            if (retPesquisa == '0') {
                trataRetPesq = "INATIVO";
            }
            else if (retPesquisa == '1') {
                trataRetPesq = "ATIVO";
            }
            else {
                trataRetPesq = "TODOS";
            }

            return trataRetPesq;
        }

    });
</script>

@*    $(function () {
        $("#edtPesquisar").on("keyup", function () {
            var valor = $(this).val().toUpperCase();
            var rows = $("#unidadesGrid tbody tr");
            if (valor) {
                
                if ($("#tipoPesquisa").val() == 1) {
                    $.each(rows, function () {
                        var td = $(this).children("td")[0];
                        if ($(td).text().indexOf(valor) < 0) {
                            $(this).hide();
                        }
                        else {
                            $(this).show();
                        }
                    });

                }
                else if ($("#tipoPesquisa").val() == 0 && valor.length > 2) {
                    $.each(rows, function () {
                        var td = $(this).children("td")[1];
                        var descricao = $(td).text().toUpperCase();
                        if (descricao.indexOf(valor.toUpperCase()) < 0) {
                            $(this).hide();
                        }
                        else {
                            $(this).show();
                        }
                    });
                }
                else if ($("#tipoPesquisa").val() == 0 && valor.length < 3) {
                    $(rows).show();
                }
            }
            else {
                $(rows).show();
            }
        });
    });
*@

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/UnidadeNow/_CadastroDivisao.cshtml
@using Amil.AsmWebCad.UI.Resources;

<div id="DivisaoModal" class="modal fade in" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog modal-sm" >
        <div class="modal-content">
            <div class="modal-header">
                Incuir Divisão da Unidade
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">
                <form class="form-horizontal" onsubmit="return false;" id="frmDivisaoUnidade">
                    <div class="row">
                        <div class="col-sm-9">
                            <label class="control-label" id="lblDivisao">Divisão</label>
                            @Html.TextBox("Divisao", "", new { @class = "form-control", @maxlength = 15 })
                        </div>
                    </div>
                    <br />
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" title="@Resource.TituloBotaoSalvar" onclick="UnidadeDivisao.IncluirDivisao();">Incluir</button>
                    <button type="reset" class="btn btn-outline btn-primary" onclick="UnidadeDivisao.Cancelar();" title="@Resource.Cancelar">@Resource.Cancelar</button>
                </div>
            </div> 

        </div>
    </div>
</div>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/UnidadeNow/_CadastroGrafico.cshtml
@model Amil.AsmWebCad.UI.Models.UnidadeNowModel;
@using Amil.AsmWebCad.UI.Resources;

<div id="GraficoModal" class="modal fade in" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog modal-lg" >
        <div class="modal-content">
            <div class="modal-header">
                Incuir Gráfico da Unidade
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">
                <form class="form-horizontal" onsubmit="return false;" id="frmGraficoUnidade">
                    <div class="row">
                            <div class="col-sm-3">
                                <legend>Fase</legend>
                                    @Html.DropDownListFor(a => a.grafico.Fase, (SelectList)ViewBag.Fase, @Resource.Selecione, (object)new { @class = "form-control" })
                                    @Html.ValidationMessageFor(a => a.grafico.Fase)
                            </div>
                                                        

                    </div>
                    <br />
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" title="@Resource.TituloBotaoSalvar" onclick="UnidadeGrafico.IncluirGrafico();">Incluir</button>
                    <button type="reset" class="btn btn-outline btn-primary" onclick="UnidadeGrafico.Cancelar();" title="@Resource.Cancelar">@Resource.Cancelar</button>
                </div>
            </div> 

        </div>
    </div>
</div>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/UnidadeNow/_GridEspecialidades.cshtml
@model IEnumerable<Amil.AppHospitais.DTO.EspecialidadeMedica>


<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Código</th>
            <th>Especialidade</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
            <tr>
                <td>
                    <label>
                        <input type="checkbox" class="" data-idEspecialidade="@item.idEspecialidade" data-codCorporativo="@item.codigoCorporativo" data-nomeEspecialidade="@item.nome" />
                    </label>
                </td>
                <td>@item.codigoCorporativo</td>
                <td>@item.nome</td>
            </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">Nenhum registro foi encontrado.</td>
            </tr>
        }
    </tbody>
</table>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/UnidadeNow/_GridUnidades.cshtml
@model List<Amil.AppHospitais.DTO.UnidadeDTO>

@if (Model != null)
{
    <table class="table table-striped table-hover" id="unidadesGrid">
        <thead>
            <tr>
                <th>Código</th>
                <th>Unidade</th>
                <th>Status</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-idUnidade="@item.Identificador">
                    <td>@item.CodCorpUnidade</td>
                    <td>@item.Descricao</td>
                    <td>@(item.Ativo ? "Ativo" : "Inativo")</td>
                    <td><a href="@Url.Action("EditarCriarUnidade", new { id = item.Identificador  })" class="glyphicon glyphicon-pencil"></a></td>
                </tr>
            }
        </tbody>
    </table>
}