ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Controllers/EspecialidadeNowController.cs
using Amil.AsmWebCad.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Amil.AppHospitais.DTO;
using Amil.AsmWebCad.Utils;
using Amil.AsmWebCad.UI.NowWCF;
using System.IO;
using Amil.AsmWebCad.UI.Helpers;
using Amil.AppHospitais.BLL;
using Amil.AppHospitais.APIClient;

namespace Amil.AsmWebCad.UI.Controllers
{
    public class EspecialidadeNowController : BaseController
    {

        public ActionResult ValidarAcesso()
        {
            JsonResult result;

            result = Json(new { Result = "true", Erro = false, Mensagem = "Acesso OK" }, JsonRequestBehavior.AllowGet);

            return result;

        }

        public ActionResult Pesquisa(int idUnidade, string limpar = "", string modal = "")
        {

            //{
            //    var especialidadeNowModel = (EspecialidadeNowModel)Session["especialidadeNowModel"];
            //    if (modal == "S")
            //    {

            //        especialidadeNowModel.Id = 1;
            //        especialidadeNowModel.Descricao = "TESTE";

            //    }
            //    else if (especialidadeNowModel == null || limpar == "S")
            //    {

            //        var especialidadeNowModel = new EspecialidadeNowModel();
            //        unidadeNowModel.Id = 0;
            //        unidadeNowModel.Nome = "";
            //        unidadeNowModel.PrimeiroAcesso = "S";

            //        Session["unidadeNowModel"] = null;


            //    }

            //    return View(unidadeNowModel);
            //}
            return View();
        }

        [HttpPost]
        public ActionResult Pesquisa(FormCollection formCollection)
        {
            JsonResult result = null;

            try
            {
                var nome = formCollection["nome"];
                var tipo = formCollection["tipoConsulta"];
                var lstSpec = new List<NowSpecialtyDTO>();
                 //var lstSpec1 = new List<NOW_ESPECIALIDADES>();
                 //lstSpec1 = new ServiceClient().EspecialidadeId(nome);
               
                var lstSpecFiltradas = new List<NowSpecialtyDTO>();
                
                var paging = formCollection.ToPagingDTO();
                PagedResult<NowSpecialtyDTO> lstSpecDTO;

                //if (tipo == "0")
                //{
                //    lstSpec = new ServiceClient().EspecialidadeNome(nome);
                //}
                //else
                //{
                //    lstSpec = new ServiceClient().EspecialidadeId(nome);
                //}
                
                //TROCAR PELA WEB-API (CONSULTA GENERICA SO SISMED WEBCAD TABELA AA_EPECIALIDADE)
                lstSpec = new ServiceClient().GetNowSpecialties();
                if (tipo == "0")
                {
                     lstSpecFiltradas = lstSpec.Where(l => l.Specialty.Contains(nome)).ToList();
                }
                else {

                    lstSpecFiltradas = lstSpec.Where(l => l.SpecialtyCode == nome).ToList();
                }

                paging.Order = "Specialty";
                lstSpecDTO = lstSpecFiltradas.ToPagedResult(paging.Offset, 15, paging.Order);

                result = JsonFromPagedList(lstSpecDTO);

            }
            catch (TimeoutException ex)
            {
                ModelState.AddModelError("Timeout", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;

        }

        public ActionResult Manutencao()
        {
            var especialidadeViewModel = new EspecialidadeNowModel();

            try
            {
                var parameters = SecurityHelper.GetRequestParams();
                var idEsp = DataParser.Parse(parameters["idEspecialidade"], 0);
                //ucEspecialidade.IdChave = specialty.SpecialtyKeyId;
                //txtSigla.Text = specialty.Acronym;
                //SpecialtyId = specialty.SpecialtyId;

                //var perfilModel = new PerfilModel();
                especialidadeViewModel.IdEspecialidade = 0;

                // Editar
                if (idEsp > 0)
                {
                    // carrega o perfil e popula os campos
                    var Esp = new ServiceClient().GetNowSpecialty(idEsp);

                    especialidadeViewModel.IdEspecialidade = Esp.SpecialtyId;
                    especialidadeViewModel.Sigla = Esp.Acronym;
                    especialidadeViewModel.Descricao = Esp.Specialty;
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(especialidadeViewModel);

        }

        [HttpPost]
        public ActionResult Manutencao(FormCollection formCollection)
        {
            return View();
        }

        public PartialViewResult CodigoBaseModal(int idEspecialidade, string nome = "")
        {
            var especialidadeNowModel = (EspecialidadeNowModel)Session["EspecialidadeNowModel"];
            //if (UnidadeNowModel == null)
            //{
            //    UnidadeNowModel = new UnidadeNowModel();

            especialidadeNowModel = new EspecialidadeNowModel();

            //especialidadeNowModel.Id = idEspecialidade;
            especialidadeNowModel.Descricao = nome;

            ViewBag.NomeBag = nome;
            //}

            return PartialView("_CodigoBaseModal");
        }

        public ActionResult ValidarAcessoPesquisa()
        {
            JsonResult result;

            try
            {
                var client = new UsuarioClient(Session);

                LoginUsuarioDTO usuarioDTO = new LoginUsuarioDTO();

                usuarioDTO.Nome = "webcad";

                var resultado = client.Listar(usuarioDTO);

                result = Json(new { Result = "true", Erro = false, Mensagem = "Acesso OK" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                result = Json(new { Result = 0, Erro = true, Mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return result;
        }


	}
}

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/EspecialidadeNow/Manutencao.cshtml
@using Amil.AsmWebCad.UI.Resources;
@model Amil.AsmWebCad.UI.Models.EspecialidadeNowModel

@{
    ViewBag.Title = "Cadastrar Especiaidade Now";  //Resource
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section SectionHead{
    @Scripts.Render("~/bundles/especialidadenow")

    <script type="text/javascript">
        $(document).ready(function () {
            EspecialidadeNow.Urls.PesquisaPerfis = '@Url.Action("Pesquisa", "EspecialidadeNow")';

            EspecialidadeNow.Mensagens.SucessoGravacao = '@Resource.MensagemSucessoGravacao';
            EspecialidadeNow.Mensagens.ConfirmacaoExclusao = '@Resource.MensagemConfirmacaoExclusao';
            PesquisaEspecialidadeNow.Mensagens.SucessoExclusao = '@Resource.MensagemSucessoExclusao';
            PesquisaEspecialidadeNow.Mensagens.ConfirmacaoExclusao = '@Resource.MensagemConfirmacaoExclusao';
            EspecialidadeNow.Titulo = 'Especialidade Now'; //Resource';
            ManutencaoEspecialidadeNow.Inicializar();

            $('#Codigo').on('input', function () {
                $(this).val(this.value.toUpperCase());
            });

        });


    </script>
}

<form class="form-horizontal" onsubmit="return false;" id="frmManutencaoEspecialidadeNow">
    <div class="panel-full">
        @Html.ValidationSummary(true)
        <div class="panel panel-primary">
            <div class="panel-heading">
                Resource.TituloFormDadosEspecialidadeNow
                <div class="pull-right" data-toggle="collapse" data-target="#pesquisaEspecialidadeNow">
                    <button type="button" class="btn btn-default btn-xs" data-toggle="button">
                        <i class="fa fa-minus-square"></i>
                    </button>
                </div>
            </div>

            <div class="panel-body collapse in" id="insereEspecialidade">
                @Html.HiddenFor(a => a.Id)
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-3">
                        <label class="control-label">Resource.EspecialidadeNow</label>
                            @Html.TextBoxFor(a => a.Descricao, (object)new { @class = "form-control", @maxlength = 70 })
                            @Html.ValidationMessageFor(a => a.Descricao)
                        </div>
                        <div class="col-lg-3">
                            <label class="control-label">Resource.Codigo</label>
                            @Html.TextBoxFor(a => a.Sigla, (object)new { @class = "form-control", @maxlength = 3 })
                            @Html.ValidationMessageFor(a => a.Sigla)
                        </div>
                    </div>
                    <br />
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <button type="button" class="btn btn-primary" title="@Resource.TituloBotaoSalvar" onclick="ManutencaoEspecialidadeNow.Salvar();">@Resource.Salvar</button>
                        <button type="reset" class="btn btn-outline btn-primary" onclick="ManutencaoEspecialidadeNow.Voltar();" title="@Resource.TituloBotaoVoltar">@Resource.Voltar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

ApptesteWipro/Amil.AppHospitais/Amil.AsmWebCad.UI/Views/EspecialidadeNow/Pesquisa.cshtml
@using Amil.AsmWebCad.UI.Resources;
@model Amil.AsmWebCad.UI.Models.EspecialidadeNowModel



@{
    ViewBag.Title = "Especialidade Now";  // Resource.Perfil_Titulo;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section SectionHead{
    @Scripts.Render("~/bundles/especialidadenow")

    <script type="text/javascript">
        $(document).ready(function () {
            Especialidade.Urls.PesquisaEspecialidades = '@Url.Action("Pesquisa", "EspecialidadeNow")';
            Especialidade.Urls.ManutencaoEspecialidade = '@Url.Action("Manutencao", "EspecialidadeNow")';
            Especialidade.Urls.ExclusaoEspecialidade = '@Url.Action("Exclusao", "EspecialidadeNow")';
            Especialidade.Urls.IncluirEspecialidade = '@Url.Action("Incluir", "EspecialidadeNow")';
            Especialidade.Urls.ValidarAcessoPesquisa = '@Url.Action("ValidarAcesso", "EspecialidadeNow")';

            Especialidade.Titulo = 'Especialidade Now';

            Especialidade.Mensagens.ConfirmacaoExclusao = '@Resource.MensagemConfirmacaoExclusaoEditavel';
            Especialidade.Mensagens.PreenchaDescricao = '@Resource.MensagemPreenchaNome';
            
            PesquisaEspecialidade.Mensagens.SucessoExclusao = '@Resource.MensagemSucessoExclusao';
            PesquisaEspecialidade.Mensagens.ConfirmacaoExclusao = '@Resource.MensagemConfirmacaoExclusao';
            PesquisaEspecialidade.Mensagens.PreenchaSistema = '@Resource.MensagemPreenchaSistema';
            PesquisaEspecialidade.Inicializar();

            $("#txtCodigoFiltro").on("input", function () {
                $(this).val(this.value.toUpperCase());
             
            });           

        });


    </script>
}

<div class="panel-full">
    <div class="pull-left">
        <div class="form-actions">
            <button title="@Resource.TituloBotaoNovo" id="btnInserir" class="btn btn-primary btnBotaoGridDireita" type="button" onclick="PesquisaEspecialidade.Incluir();">
                <i class="glyphicon glyphicon-plus"></i>
            </button>
        </div>
    </div>
    <div id="dttEspecialidades" class="dataTables_wrapper form-inline">
        <table id="grvEspecialidades" style="cursor: pointer" data-dtid="idEspecialidade" class="table table-striped table-bordered dataTable">
            <thead>
                <tr>
                    <th data-dtaction="Acoes" data-column-class="align-mid width-2">@Resource.Acoes</th>
                    <th data-dtcolumn="Specialty" data-column-class="align-left width-40">@Resource.Nome</th>
                    <th data-dtcolumn="Acronym" data-column-class="align-mid width-10">Sigla</th>
                    <th data-dtcolumn="SpecialtyId" data-column-class="hide" ></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>